export const proteinAllergies = [
    "Egg Whites",
    "Eggs",
    "Fish",
    "Full Fat Plain Nut Milk",
    "Full Fat Plain Yogurt",
    "Whole Fat Plain Milk"
];

export const fvAllergies = [
    "Acai Berry",
    "Apples",
    "Apricot",
    "Avocado",
    "Bananas",
    "Blackberry",
    "Blueberry",
    "Cantaloupe",
    "Cherries",
    "Dragon Fruit",
    "Feijoa",
    "Guanabana",
    "Grapefruit",
    "Guava",
    "Honeydew",
    "Kiwi",
    "Mangosteen",
    "Melon",
    "Mango",
    "Mandarin",
    "Orange",
    "Lychees",
    "Nectarine",
    "Papaya",
    "Passion Fruit",
    "Peaches",
    "Pears",
    "Persimmons",
    "Pineapples",
    "Plums",
    "Raspberry",
    "Strawberry",
    "Tangerines",
    "Watermelon",

    // Vegetables
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Beets",
    "Bell Peppers",
    "Broccoli",
    "Brussels Sprouts",
    "Bok Choy",
    "Cabbage",
    "Carrots",
    "Cauliflower",
    "Collard Greens",
    "Jicama",
    "Eggplant",
    "Kale",
    "Kohlrabi",
    "Mustard Greens",
    "Napa Cabbage",
    "Okra",
    "Plantain",
    "Pumpkin",
    "Radish",
    "Rutabagas",
    "Squash",
    "Tomatoes",
    "Turnips",
    "Zucchini",
]